### ISSUE TITLE
Make parallel keyword usage more robust

### ISSUE THREAD

**Issue by pantaray** [esi-neuroscience/syncopy#161]
Currently, using `parallel = True` in meta-functions causes multi-processing errors in `LocalCluster`s.

**Comment by pantaray** [comment]
This seems to be connected to a general namespace problem of dask's `LocalCluster` objects. I think we can close this one, @tensionhead ?

**Comment by tensionhead** [comment]
Phew, but does that mean we can't support parallel computing on single machines atm?

**Comment by pantaray** [comment]
Nope, it just means that launching meta-functions directly from the interpreter with using `parallel=True` (i.e., something like `>>> freqanalysis(...,parallel=True)` probably fails on local machines. However, invoking the `LocalCluster` by any other means (e.g., using `esi_cluster_setup` prior to launching `freqanalysis`) works as expected. 

I can look further into this (maybe don't allow launching a cluster if the namespace is `__main__`?) but the only "solution" I can think of is catching the attempt to fire up a `LocalCluster` in a script (and maybe print some info how to circumvent this). Should we put this on the todo list for our next minor release?

**Comment by tensionhead** [comment]
I tried launching a syncopy Python script calling the `connectivity` frontend with `parallel=True` from my local Ubuntu linux, and I got a ton of error messages:
```bash
python3 dev_frontend.py 
Syncopy <input_validators> WARNING: option `foo` has no effect in `connectivity`!
Syncopy <connectivity> INFO: Automatic FFT frequency selection from 0.0Hz to 500.0Hz
Syncopy <validate_taper> INFO: Using 14 taper(s) for multi-tapering
Syncopy <compute> WARNING: trial-averaging only supports sequential writing!
Syncopy <input_validators> WARNING: option `foo` has no effect in `connectivity`!
Syncopy <connectivity> INFO: Automatic FFT frequency selection from 0.0Hz to 500.0Hz
Syncopy <validate_taper> INFO: Using 14 taper(s) for multi-tapering
Syncopy <input_validators> WARNING: option `foo` has no effect in `connectivity`!
Syncopy <connectivity> INFO: Automatic FFT frequency selection from 0.0Hz to 500.0Hz
Syncopy <validate_taper> INFO: Using 14 taper(s) for multi-tapering
Syncopy <compute> WARNING: trial-averaging only supports sequential writing!
Syncopy <compute> WARNING: trial-averaging only supports sequential writing!
Syncopy <input_validators> WARNING: option `foo` has no effect in `connectivity`!
Syncopy <connectivity> INFO: Automatic FFT frequency selection from 0.0Hz to 500.0Hz
Syncopy <validate_taper> INFO: Using 14 taper(s) for multi-tapering
Syncopy <input_validators> WARNING: option `foo` has no effect in `connectivity`!
Syncopy <connectivity> INFO: Automatic FFT frequency selection from 0.0Hz to 500.0Hz
Syncopy <validate_taper> INFO: Using 14 taper(s) for multi-tapering
Syncopy <compute> WARNING: trial-averaging only supports sequential writing!
Syncopy <compute> WARNING: trial-averaging only supports sequential writing!
/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/site-packages/distributed/node.py:151: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 46661 instead
  warnings.warn(
/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/site-packages/distributed/node.py:151: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 33849 instead
  warnings.warn(
Task exception was never retrieved
future: <Task finished name='Task-14' coro=<_wrap_awaitable() done, defined at /home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/asyncio/tasks.py:688> exception=RuntimeError('\n        An attempt has been made to start a new process before the\n        current process has finished its bootstrapping phase.\n\n        This probably means that you are not using fork to start your\n        child processes and you have forgotten to use the proper idiom\n        in the main module:\n\n            if __name__ == \'__main__\':\n                freeze_support()\n                ...\n\n        The "freeze_support()" line can be omitted if the program\n        is not going to be frozen to produce an executable.')>
Traceback (most recent call last):
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/site-packages/distributed/core.py", line 305, in _
    await self.start()
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/site-packages/distributed/nanny.py", line 295, in start
    response = await self.instantiate()
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/site-packages/distributed/nanny.py", line 378, in instantiate
    result = await self.process.start()
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/site-packages/distributed/nanny.py", line 575, in start
    await self.process.start()
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/site-packages/distributed/process.py", line 34, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/site-packages/distributed/process.py", line 202, in _start
    process.start()
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Task exception was never retrieved
future: <Task finished name='Task-11' coro=<_wrap_awaitable() done, defined at /home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/asyncio/tasks.py:688> exception=RuntimeError('\n        An attempt has been made to start a new process before the\n        current process has finished its bootstrapping phase.\n\n        This probably means that you are not using fork to start your\n        child processes and you have forgotten to use the proper idiom\n        in the main module:\n\n            if __name__ == \'__main__\':\n                freeze_support()\n                ...\n\n        The "freeze_support()" line can be omitted if the program\n        is not going to be frozen to produce an executable.')>
Traceback (most recent call last):
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/site-packages/distributed/core.py", line 305, in _
    await self.start()
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/site-packages/distributed/nanny.py", line 295, in start
    response = await self.instantiate()
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/site-packages/distributed/nanny.py", line 378, in instantiate
    result = await self.process.start()
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/site-packages/distributed/nanny.py", line 575, in start
    await self.process.start()
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/site-packages/distributed/process.py", line 34, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/site-packages/distributed/process.py", line 202, in _start
    process.start()
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Task exception was never retrieved
future: <Task finished name='Task-13' coro=<_wrap_awaitable() done, defined at /home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/asyncio/tasks.py:688> exception=RuntimeError('\n        An attempt has been made to start a new process before the\n        current process has finished its bootstrapping phase.\n\n        This probably means that you are not using fork to start your\n        child processes and you have forgotten to use the proper idiom\n        in the main module:\n\n            if __name__ == \'__main__\':\n                freeze_support()\n                ...\n\n        The "freeze_support()" line can be omitted if the program\n        is not going to be frozen to produce an executable.')>
Traceback (most recent call last):
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/site-packages/distributed/core.py", line 305, in _
    await self.start()
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/site-packages/distributed/nanny.py", line 295, in start
    response = await self.instantiate()
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/site-packages/distributed/nanny.py", line 378, in instantiate
    result = await self.process.start()
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/site-packages/distributed/nanny.py", line 575, in start
    await self.process.start()
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/site-packages/distributed/process.py", line 34, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/site-packages/distributed/process.py", line 202, in _start
    process.start()
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/home/whir/miniconda3/envs/syncopy-acme/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```
So at least for me, locally, I can't run syncopy in a parallel fashion from the shell nor interpreter. I could try running it from a jupyter notebook @pantaray ?!

**Comment by pantaray** [comment]
Yupp, this is consistent w/dask's `LocalCluster` namespace problem. The very last piece of the exception addresses the problem (`...you have forgotten to use the proper idiom in the main module: `), compare, e.g., https://github.com/dask/distributed/issues/4751 
A simple fix is wrapping the frontend call in a `if __name__ == "__main__"` block, e.g., 
```python
# Import package
import syncopy as spy

# Import artificial data generator
from syncopy.tests.misc import generate_artificial_data

# Prepare code to be executed using, e.g., iPython's `%run` magic command
if __name__ == "__main__":

    # Test stuff within here...
    data = generate_artificial_data(nTrials=5, nChannels=16, equidistant=True, inmemory=False)
    spec = spy.freqanalysis(data, method="mtmfft", output="pow", parallel=True)
```
works as expected (as does invoking `esi_cluster_setup` before calling `freqanalysis`). Again, the only "solution" could be trying to prevent starting a not properly wrapped `LocalCluster` so that this error is not triggered in the first place.

**Comment by pantaray** [comment]
Good point raised by @tensionhead : ensure that any introduced namespace gymnastics don't break Jupyter notebook functionality.
